### PR TITLE
tests: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR. However, there are a few problems with this approach:
1. We removed the lockfile on purpose in #3792 due to issues with it inside of npm.
2. We intentionally don't upgrade `npm` in CI to make sure our builds pass with the versions included by default in respective Node.js versions as that's what usually people use.
3. This change doesn't speed up the build which is the main supposed advantage of `npm ci` vs `npm install`; compare https://travis-ci.org/jquery/jquery/builds/369211845 & https://travis-ci.org/jquery/jquery/builds/367872474

In light of the above, I don't think we'll want to switch to `npm ci`.

**Comment by DanielRuf** [comment]
Right. We just have to trigger a build to compare the results.

Thanks for the feedback.

**Comment by DanielRuf** [comment]
> We removed the lockfile on purpose in #3792 due to issues with it inside of npm.

Which was fixen in npm 5.6 ;-) https://github.com/npm/npm/issues/18135#issuecomment-351085000
Also see https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by mgol** [comment]
We're aware of the supposed fixes for that in npm 5.6 but #17722 is still open and there are comments indicating this is still an issue when working cross-platform.

Besides, we haven't had many problems with sub-dependencies misbehaving so it seems our contributors would suffer more from lockfile issues rather than dependencies changing under us.

**Pull request closed without merging**
