### PR TITLE
Build: ESLint: forbid unused function parameters

### PR DESCRIPTION
**Pull request by mgol**
### Summary ###

This commit requires all function parameters to be used, not just the last one.
In cases where that's not possible as we need to match an external API, there's
an escape hatch of prefixing an unused argument with `_`.

This change makes it easier to catch unused AMD dependencies and unused
parameters in internal functions the API of which we may change at will, among
other things.

Unused AMD dependencies have been removed as part of this commit.

What do you think? If you agree this change is worthwhile, should we add that rule to `eslint-config-jquery`?

### Checklist ###

* [x] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
* ~~New tests have been added to show the fix or feature works~~
* [x] Grunt build and unit tests pass locally with these changes
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~

### CODE REVIEW

**Comment by mgol** [comment]
@Krinkle AMD is the biggest use case but we're likely to get rid of it soon anyway in favor of standard ES modules. It's also useful for lots of internal functions, though. As @timmywil said, it doesn't help with functions with signatures bound by external contracts but we have lots of internal functions and it's easy to miss a specific parameter is not required anymore and could be removed with size gains. It forces you to think each time you need to prefix a parameter whether you can remove it or not. Therefore, I see gains beyond AMD.

In this PR I only had to use the `_` workaround in 15 places in the entire jQuery source, 8 of which are `jQuery.each` & 1 `jQuery.map`, leaving only 6 "regular" cases.

If you think this rule is not a good fit for QUnit, I could leave it as an override here in jQuery repo, although we're not using any overrides at the moment - but I see [QUnit is](https://github.com/qunitjs/qunit/blob/master/.eslintrc.json) and quite a lot at that.

**Comment by mgol** [comment]
I wrote a comment and it disappeared, argh...

jQuery's AMD is the biggest beneficent of this new rule but we'll most likely migrate to ES modules so it will stop being so in the future. I see other gains, though - while, as @timmywil noted, functions bound by external contracts need the `_` prefixes, there are lots of internal ones and it's sometimes easy to miss a particular parameter may no longer be used & can be removed.

In my PR I only had to add the `_` prefix in 15 places, 8 of which are `jQuery.each` & 1 `jQuery.map`, leaving 6 "regular" cases.

If you think this rule is not a good fit for QUnit, I may just leave an override here but we haven't been using overrides so far. I see [QUnit is](https://github.com/qunitjs/qunit/blob/master/.eslintrc.json), though, and quite a lot at that; QUnit also uses the `eslint:recommended` config which we don't. I wonder how big a gain for QUnit is that it uses the `jquery` config; in the past we thought of it as a preset common for all jQuery Foundation projects but that hasn't materialized. At the moment, I think, it's mostly a few jQuery projects to which similar people contribute: Core, Migrate, Color, and QUnit.

**Comment by mgol** [comment]
I wrote a comment and it disappeared, argh...

jQuery's AMD is the biggest beneficent of this new rule but we'll most likely migrate to ES modules so it will stop being so in the future. I see other gains, though - while, as @timmywil noted, functions bound by external contracts need the `_` prefixes, there are lots of internal ones and it's sometimes easy to miss a particular parameter may no longer be used & can be removed.

In my PR I only had to add the `_` prefix in 15 places, 8 of which are `jQuery.each` & 1 `jQuery.map`, leaving 6 "regular" cases.

If you think this rule is not a good fit for QUnit, I may just leave an override here but we haven't been using overrides so far. I see [QUnit is](https://github.com/qunitjs/qunit/blob/master/.eslintrc.json), though, and quite a lot at that; QUnit also uses the `eslint:recommended` config which we don't. I wonder how big a gain for QUnit is that it uses the `jquery` config; in the past we thought of it as a preset common for all jQuery Foundation projects but that hasn't materialized. At the moment, I think, it's mostly a few jQuery projects to which similar people contribute: Core, Migrate, Color, and QUnit.

**Comment by mgol** [comment]
I wrote a comment and it disappeared, argh...

jQuery's AMD is the biggest beneficent of this new rule but we'll most likely migrate to ES modules so it will stop being so in the future. I see other gains, though - while, as @timmywil noted, functions bound by external contracts need the `_` prefixes, there are lots of internal ones and it's sometimes easy to miss a particular parameter may no longer be used & can be removed.

In my PR I only had to add the `_` prefix in 15 places, 8 of which are `jQuery.each` & 1 `jQuery.map`, leaving 6 "regular" cases.

If you think this rule is not a good fit for QUnit, I may just leave an override here but we haven't been using overrides so far. I see [QUnit is](https://github.com/qunitjs/qunit/blob/master/.eslintrc.json), though, and quite a lot at that; QUnit also uses the `eslint:recommended` config which we don't. I wonder how big a gain for QUnit is that it uses the `jquery` config; in the past we thought of it as a preset common for all jQuery Foundation projects but that hasn't materialized. At the moment, I think, it's mostly a few jQuery projects to which similar people contribute: Core, Migrate, Color, and QUnit.

**Comment by mgol** [comment]
I wrote a comment and it disappeared, argh...

jQuery's AMD is the biggest beneficent of this new rule but we'll most likely migrate to ES modules so it will stop being so in the future. I see other gains, though - while, as @timmywil noted, functions bound by external contracts need the `_` prefixes, there are lots of internal ones and it's sometimes easy to miss a particular parameter may no longer be used & can be removed.

In my PR I only had to add the `_` prefix in 15 places, 8 of which are `jQuery.each` & 1 `jQuery.map`, leaving 6 "regular" cases.

If you think this rule is not a good fit for QUnit, I may just leave an override here but we haven't been using overrides so far. I see [QUnit is](https://github.com/qunitjs/qunit/blob/master/.eslintrc.json), though, and quite a lot at that; QUnit also uses the `eslint:recommended` config which we don't. I wonder how big a gain for QUnit is that it uses the `jquery` config; in the past we thought of it as a preset common for all jQuery Foundation projects but that hasn't materialized. At the moment, I think, it's mostly a few jQuery projects to which similar people contribute: Core, Migrate, Color, and QUnit.

**Comment by Krinkle** [comment]
@mgol Yeah, makes sense to share with e.g. jquery migrate. Using the preset for that makes sense.

I'd say don't worry about QUnit in that case, we can disable things as needed, no problem.

**Comment by mgol** [comment]
For anyone reading this, GitHub has messed the order of the comments and some older comments display below the newer ones.

**Comment by trentmwillis** [comment]
My two cents: I don't think it would impact QUnit much, if it becomes a pain we can opt-out as @Krinkle mentions above.

**Comment by mgol** [comment]
I submitted https://github.com/jquery/eslint-config-jquery/pull/14 for the config changes. Please review, after publishing an update I'll change this PR.

**Comment by mgol** [comment]
Cherry-picked to `3.x-stable` in d7e13f128a4965f5d2bf510dc2314faa266f9dd7.

**Pull request merged**
