### PR TITLE
Docs: Replace `#NUMBER` Trac issue references with `trac-NUMBER`

### PR DESCRIPTION
**Pull request by mgol**
### Summary ###

The GitHub UI treats `#NUMBER` as referring to its own issues which is confusing
when in jQuery source it's usually referring to the old deprecated Trac instance
at https://bugs.jquery.com. This change replaces all such Trac references with
`trac-NUMBER`.

A few of the references came with the Sizzle integration and referred to the
Sizzle GitHub bug tracker. Those have been replaced with full links instead.

A new entry describing issue reference conventions has been added to README.

When this gets accepted, I'll submit a similar PR against the `3.x-stable` branch to keep them aligned.

### Checklist ###

* ~~New tests have been added to show the fix or feature works~~
* [x] Grunt build and unit tests pass locally with these changes
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~

### CODE REVIEW

**Review by timmywil — APPROVED** [review]
I hope this wasn't too tedious. Thanks!

**Review by Mansalol — APPROVED** [review]

**Comment by mgol** [comment]
Landed on `main` in 5d5ea015114092c157311c4948f7cc3d8c8e7f8a. The `3.x-stable` version is submitted as a separate PR: #4994.

**Comment by mgol** [comment]
@Mansalol Don’t spam our repo with random unrelated comments. This just wastes everyone’s time.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Pull request merged**
