### PR TITLE
Ajax: Get URL variables

### PR DESCRIPTION
**Pull request by Jakemichaeldrew**

### CODE REVIEW

**Comment by Jakemichaeldrew** [comment]
Why does the CLA not work, I have signed it several times and followed the instructions here http://contribute.jquery.org/CLA/ and here http://contribute.jquery.org/CLA/status/?repo=jquery&sha=d8613d790c1e8811790602cbb7780abc5d1d6444

**Comment by dmethvin** [comment]
Most likely, your original signature (the first one you ever did) doesn't match the one in your commit.

**Comment by mzgol** [comment]
Hey @Jakemichaeldrew, please don't submit that many pull requests for the same thing. You should read https://contribute.jquery.org/commits-and-pull-requests/ to know more about how to submit pull requests; in particular, it's not advisable to introduce changes on the `master` branch - you should create a separate branch and `master` should be kept up to date with the main jQuery repository.

You can push changes to the pull request just by committing to the branch from which you reported the pull request, no need to report another and another one.

That said, we don't currently plan introducing such new features, especially ones that are easily implemented as a plugin or an external library.

**Comment by dmethvin** [comment]
In this case especially, the functionality isn't really jQuery specific so it could (and should!) be implemented independently of jQuery. 

https://github.com/jquery/jquery/wiki/Adding-new-features

**Comment by mzgol** [comment]
@Jakemichaeldrew As for the CLA, your commits needs to be signed by your full name and currently it's just "jakemichaeldrew". You need to amend the commit (and please change your Git settings to contain the proper info).

In the future, it's better to first report an issue to see if the PR is going to be accepted.

**Comment by Jakemichaeldrew** [comment]
Thanks, :smile:

**Pull request closed without merging**
