### PR TITLE
Handle potential null result for leverageNative

### PR DESCRIPTION
**Pull request by radar**
### Summary ###

Possible fix for #4417.

### Checklist ###

* [x] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
* [ ] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

----

I am not sure where or how to test that this fix works. Help / direction would be appreciated.

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR!

The most important part here is how to test this change, though, the source change itself is simple and it has already been suggested by @gibson042 in #4417.

Do you want to write a test?

**Comment by radar** [comment]
I am not sure where to begin writing a test.

Perhaps I could copy over the HTML + JS from https://jsbin.com/wuqumigiya/edit?html,js,console and assert within `test/unit/event.js` that the error does not happen there.

What do you think?

**Comment by mgol** [comment]
jQuery only runs unit tests in CI, we don't have any integration test setup. This poses problems in situations like this one as some focus-related bugs are specific to native events and emulating the behavior in unit tests is non-trivial.

I don't know how to write the test, I tried for a while in the past but I didn't manage to do it before I run out of time. So I can't provide a very concrete advise, unfortunately.

You would need to add a test in [`test/unit/event.js`](https://github.com/jquery/jquery/blob/master/test/unit/event.js), you can have a look at existing focus tests there, maybe you'll find some inspiration.

**Comment by ryuran** [comment]
@radar @mgol After several months It style broken even if the fix is known. I hope it will be merged soon.
We currently are not able to update jQuery because lot of our tests fail on this `value`of undefined.

**Comment by mgol** [comment]
@ryuran We still need to figure out a test for this. If you can help with that then the PR will surely be merged sooner.

**Comment by mgol** [comment]
I submitted a version with a test so I'll close this PR. Sorry! See #4799.

**Pull request closed without merging**
