### PR TITLE
Single quotes not allowed. Should finally pass integration tests

### PR DESCRIPTION
**Pull request by david-mark**
### Checklist ###
Mark an `[x]` for completed items, if you're not sure leave them unchecked and we can assist.

* [ x] All authors have signed the CLA at https://contribute.jquery.com/CLA/
* [ N/A] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

Thanks! Bots and humans will be around shortly to check it out.

### CODE REVIEW

**Comment by david-mark** [comment]
Appears to have passed all tests this time. :)

**Comment by dmethvin** [comment]
@david-mark Each time you open a pull request or push new commits to it, there are more than 3,300 people notified. There's no good reason for submitting PRs with style or other CI errors, you can run the checks locally.

**Comment by david-mark** [comment]
> @david-mark Each time you open a pull request or push new commits to it, there are more
> than 3,300 people notified. There's no good reason for submitting PRs with style or other CI
> errors, you can run the checks locally.

Wouldn't need to keep doing it, but "The Brain" keeps closing them before we've finished the discussion (started about five pull requests ago). Please leave this one alone as it passed all integration tests. Thanks!

**Comment by david-mark** [comment]
And there he goes again. :(

**Comment by gibson042** [comment]
We've been clear that discussion needs to take place in an issue, not a pull request—and especially not a pull request from your master branch full of unrelated whitespace changes.

**Comment by david-mark** [comment]
Will open an issue regarding the window vs. global object confusion when/if I have time. Shouldn't have taken more than a few posts and replies for us to be on the same page on that.

Good luck!

**Comment by dmethvin** [comment]
:+1: Issues are definitely the way to work this out.

**Comment by david-mark** [comment]
I agree as this is taking more discussion than I originally figured.

Here you go:

https://github.com/jquery/jquery/issues/3426

**Pull request closed without merging**
