### PR TITLE
Tests: Update the loader so test pages always get jQuery

### PR DESCRIPTION
**Pull request by gibson042**
This helped work on gh-3487.

### CODE REVIEW

**Comment by markelog** [comment]
Why is this needed?

**Comment by gibson042** [comment]
It's not _needed_, but being able to open the iframe-test pages in a browser tab and make the same jQuery calls as their respective tests is definitely a worthwhile convenience, especially when we can get it without breaking anything. But absent this fix, opening e.g. test/data/offset/absolute.html generates `Uncaught TypeError: Cannot read property 'config' of undefined` from https://github.com/jquery/jquery/blob/a8816caf26c0acc7067cd5bad9c03cfb54e54979/test/jquery.js#L11 , and subsequently fails to load jQuery.

**Comment by markelog** [comment]
Cool! Could you put that explanation in the commit? :)

**Comment by gibson042** [comment]
Done.

**Pull request merged**
