### PR TITLE
Tests: don't use deprecated argument in test declaration

### PR DESCRIPTION
**Pull request by markelog**
@FagnerMartinsBrack hope you will be happy about this :-).

Did it with CST script manipulation - https://github.com/markelog/qunit-migration/blob/master/src/migration.js

@scottgonzalez, @jzaefferer, @Krinkle
I suppose it would be useful if qunit would provide scripts like that, here it only replaces deprecated argument, but it could do a lot more.

@nzakas i guess this could be another example of manipulation with CST.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
> @FagnerMartinsBrack hope you will be happy about this :-).

I won't be "happy", just thought it would be useful reminding about it ¬¬

**Comment by jzaefferer** [comment]
There's a similar tool for migrating to the QUnit 2.0 API, though using regex replace: https://github.com/apsdehal/qunit-migrate

Surely would be good to have one reliable tool that handles the full migration.

**Comment by markelog** [comment]
@FagnerMartinsBrack
> just thought it would be useful reminding about it ¬¬

It totally was! Your remainder prompt me to do this

> There's a similar tool for migrating to the QUnit 2.0 API

That sounds cool, although regexs aren't, it seems though, it missing this kind of manipulation.

**Comment by dmethvin** [comment]
This LGTM. It would be convenient if `QUnit.config.requireExpect` let you require only the `expect()` format instead of the function arg, but I doubt this will be a problem in future tests since people tend to copy whatever style is nearby.

**Comment by mzgol** [comment]
LGTM.

**Comment by markelog** [comment]
In weekend i will try to apply manipulation from the module that @jzaefferer mentioned

**Pull request closed without merging**
