### PR TITLE
Css: Restore the hack to get pixels for .css('width') etc.

### PR DESCRIPTION
**Pull request by mzgol**
This hack turns out to be needed by Android 4.0-4.3

Refs gh-1815
Refs gh-1820

### CODE REVIEW

**Comment by mzgol** [comment]
This is ready for initial review, I still have one problem, though. This patch makes the test fail in Android 2.3 & Chrome (40 & Canary) in the [bodyBackground test](https://github.com/jquery/jquery/blob/a5e1c9b44c971fd7046d9a95bd0810e50840b663/test/unit/support.js#L29). The added support test returns `false` in this case as in both Chrome & Android 2.3 the computed `marginRight` is then equal to `50%`, not `4px`.

It seems there's a race condition here; if some operations are executed in the "right" order the browser forgets how to compute styles. O_o Firefox is OK here.

If anyone has any idea what might be a cause of this, that'd be great. Otherwise I'll have to create a simpler test case and probably submit a Chrome issue. :/

**Comment by dmethvin** [comment]
Maybe @mikesherov has some idea, I'm stumped. Otherwise it looks like this is putting back the big lump of code we took out so if we have to, we have to.

**Comment by mzgol** [comment]
> Maybe @mikesherov has some idea, I'm stumped. Otherwise it looks like this is putting back the big lump of code we took out so if we have to, we have to.

Yeah but I'd like to run a support test and apply the hack only when needed as it's costly. So I'm a little surprised that Chrome is buggy but only in rare circumstances that we stumble upon in tests. :/

**Comment by mzgol** [comment]
Stupid me, it was caused by the `div { display: inline }` CSS rule in the `bodyBackground.html` template. I added an explicit `display:block` to the div CSS and now it works fine. \o/

Ready to merge unless anyone has any remarks. :)

**Comment by mzgol** [comment]
If no one will object, I'll land this probably after next Monday meeting.

**Comment by mzgol** [comment]
Currently it adds 130 bytes; it'd be good to compress it.

**Comment by mzgol** [comment]
+119 bytes.

Why do we pass `null` as the second parameter to `getComputedStyle` anyway? Does anything besides ancient Firefox versions require it? Since even Android 2.3 seems to go fine with it...

**Comment by markelog** [comment]
> Why do we pass null as the second parameter to getComputedStyle anyway? 

See https://developer.mozilla.org/en-US/docs/Web/API/Window.getComputedStyle, pretty safe to remove it now.

But it feels like a different issue, different commit, PR etc. Like with can try to omit third argument of `addEventListener` method for `master` branch and see where it would lead us. 

And maybe for other native methods as well, but i would do in separate PR.

**Comment by gibson042** [comment]
>  it'd be good to compress it

Have you tried combining the `if ( computed )` blocks? `jQuery.swap` also comes to mind, and the whole css support suite looks rife with duplication (though cleaning that is probably best suited to another PR).

**Comment by mzgol** [comment]
@markelog 
>> Why do we pass null as the second parameter to getComputedStyle anyway? 
>
>See https://developer.mozilla.org/en-US/docs/Web/API/Window.getComputedStyle, pretty safe to remove it now.
>
>But it feels like a different issue, different commit, PR etc.

Sure, that was a side-question, I didn't mean to do it here.

@gibson042 
> Have you tried combining the `if ( computed )` blocks?

What `if ( computed )` blocks?

The `boxSizingReliable` & `pixelPosition` tests require a different setup than `pixelMarginRight` (see what `width` is set in both cases on the div). Conflating them would mean stacking 2 layouts which is not good.

**Comment by mzgol** [comment]
@gibson042 I could reimplement some of those tests to use `jQuery.swap` and be shorter but I'd still want to keep the logic of computing both `pixelPosition` & `boxSizingReliable` in one go. As you said - that's rather a question for a separate PR.

**Comment by markelog** [comment]
@mzgol created - https://github.com/jquery/jquery/issues/2047

**Comment by gibson042** [comment]
> What `if ( computed )` blocks?

[src/css/curCSS.js#L18](https://github.com/mzgol/jquery/blob/97330e00f97a34cca6b71e80d497cb4975b0b239/src/css/curCSS.js#L18-22). And the same file for `jQuery.swap`: [#L36-48](https://github.com/mzgol/jquery/blob/97330e00f97a34cca6b71e80d497cb4975b0b239/src/css/curCSS.js#L36-48).

> The `boxSizingReliable` & `pixelPosition` tests require a different setup than `pixelMarginRight` (see what `width` is set in both cases on the div)

That's true, but maybe the former could use height. There are many possibilities, all to be explored elsewhere.

**Comment by mzgol** [comment]
> That's true, but maybe the former could use height. There are many possibilities, all to be explored elsewhere.

Sure. I just want to get Android>2.3 green for now, we can tweak it later, even after the beta. :)

**Comment by mgol** [comment]
This has been backported to `1.12.0` & `2.2.0` so I changed the milestone (it used to say `3.0.0`).

**Pull request merged**
