### PR TITLE
Build: bower.json: remove moot `version` field

### PR DESCRIPTION
**Pull request by cvrebert**
Per https://github.com/bower/bower.json-spec/commit/a325da3d79baab018c572d75dc1781b12322f6cd

### CODE REVIEW

**Comment by dmethvin** [comment]
Hmmm, the bower.json file was supposed to disappear and be generated by the release script, since the dev repo is not usable directly.

**Comment by cvrebert** [comment]
Yes, this PR modifies the release script

**Comment by dmethvin** [comment]
You can tell how much I paid attention! Carry on.

**Comment by timmywil** [comment]
Thanks @cvrebert!

**Comment by stevemao** [comment]
Why? Since your using a script, it doesn't need any extra effort. You don't need to change this manually. And in the future you'll have to add this back for bower registry.

**Pull request closed without merging**
