### PR TITLE
Callbacks: Prevent add() from unlocking with-memory lists

### PR DESCRIPTION
**Pull request by gibson042**
Fixes gh-3469

### CODE REVIEW

**Comment by mgol** [comment]
I can't find any documentation that would explain why `callbacks.add(fn)` on a locked `callbacks` object is supposed to run the function. Is the documentation lacking or am I just not seeing it?

**Comment by dmethvin** [comment]
> memory: Keeps track of previous values and will call any callback added after the list has been fired right away with the latest "memorized" values (like a Deferred). https://api.jquery.com/jQuery.Callbacks/

> If the Callbacks object is created with the "memory" flag as its argument, additional functions may be added and fired after the callback list is locked. https://api.jquery.com/callbacks.lock/

Not sure if that makes total sense to me, but those are the docs.

**Comment by gibson042** [comment]
Right, it's actually the difference between `lock` and `disable`.

**Comment by dmethvin** [comment]
Yeah, mainly trying to think of specific use cases for all the Callbacks options. Clearly we haven't even probed them all for core. :)

**Comment by gibson042** [comment]
This broke an effects test; I'm investigating now. http://swarm.jquery.org/job/4519

**Pull request merged**
