### PR TITLE
Changed event.js to add "code" property to keyboard event object

### PR DESCRIPTION
**Pull request by tmybr11**
### Summary ###

Added the "code" property to the Event object passed to keyboard-triggered event handlers, as suggested on [#3978](https://github.com/jquery/jquery/issues/3978).

### Checklist ###

* [x] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
* [ ] New tests have been added to show the fix or feature works
* [x] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by dmethvin** [comment]
Not all properties that we lazy-copy are on all events that the browser can generate, and (at least last I checked) not all the properties are supported by all browsers. We'd need a matrix of event names and valid properties for the event by browser that could cover at least most of them.

To ensure we copy correctly from a native event we would need to dispatch a native event, and the mechanism to do that is browser-dependent as well right now--some support the newer event constructors and some only support the DOM2 `document.createEvent()` interface. I am not sure it's even possible to set all the properties we want to test through either.

**Comment by mgol** [comment]
@dmethvin My main worry is that some future refactor that will move this code to a different place will lose one of the properties and we won't notice. To prevent that we don't really need to test with real event objects, just mocking it would suffice.

Obviously, that would amount to just duplicating the event name list in tests without testing the substance but it still seems a little bit more secure than what we have now.

**Comment by tmybr11** [comment]
I will update the API docs asap and I can also add a new test if you think it will be necessary for this update.

**Comment by timmywil** [comment]
We could just do a super-dumb test and make sure that all of these properties are actually on the jQuery.Event prototype.

**Comment by mgol** [comment]
@timmywil Yeah, something like that would be enough here.

@tmybr11 What we're talking about applies to all properties so your PR is fine, the test we're talking about is a matter for another PR/commit.

**Pull request merged**
