### PR TITLE
Fix various spelling mistakes

### PR DESCRIPTION
**Pull request by bperel**

### CODE REVIEW

**Comment by arthurvr** [comment]
You shouldn't create a new PR to update it, you can just update the existing one ;)

The changes here look good, but you'll need to [sign the CLA](http://contribute.jquery.org/CLA/status/?repo=jquery&sha=0947943116b92ce179ceef45fd3bed8b8adeee2f).

**Comment by bperel** [comment]
I have signed the CLA but although my email address and name match my Git config the "CLA Verification Results" page says "The following authors don't have appropriate CLA signatures", followed with my info. Is there a delay after someone  sends the CLA form ?

**Comment by mzgol** [comment]
The signature looks OK to me. @scottgonzalez, any idea why the check fails?

**Comment by scottgonzalez** [comment]
> The signature looks OK to me. @scottgonzalez, any idea why the check fails?

The first signature for the CLA is "Bruno Pérel" which doesn't match because the accent is not present in the commit name.

**Comment by bperel** [comment]
Thanks @scottgonzalez , should be good now :)

**Comment by arthurvr** [comment]
Thanks @bperel :) Looks good to me.

**Comment by mzgol** [comment]
@bperel Thx, landed.

**Pull request closed without merging**
