### PR TITLE
test

### PR DESCRIPTION
**Pull request by jqguy**
test please leave open for 24 hours

### CODE REVIEW

**Comment by arthurvr** [comment]
Please don't create test pull requests. This just landed in 3000 mailboxes :)

**Comment by jqguy** [comment]
I don't listen to people who aren't involved with a repo. if you don't like test pull requests (which make your repo look popular!) please somebody from the team confirm

**Comment by jqguy** [comment]
can anyone merge me im demoing github to somebody

**Comment by markelog** [comment]
Please don't do that

**Comment by timmywil** [comment]
@jqguy 

First of all, why not? There's no reason not to listen to capable people who aren't officially involved with a repo in open source. We rely on those that aren't for help in developing all of our projects.

Secondly, @arthurvr is a jQuery team member and you should listen to him.

Third, don't do that. You can train someone on github with your own repos.

**Pull request closed without merging**
