### PR TITLE
Core: Support non-browser environments

### PR DESCRIPTION
**Pull request by mzgol**
Fixes gh-2133
Fixes gh-2501
Closes gh-2504
Refs gh-1950
Refs gh-1949
Refs gh-2397
Refs gh-1537
Refs gh-2504
Refs 842958e7aecd0d75a7ee9e2aaec83457701aa2f3

Second commit adds support for non-browser environments. Message of the first commit:

Core:CSS: Attach test nodes to documentElement, not body

Attaching test divs to document.documentElement instead of document.body
used to cause issues in jQuery 1.x; jQuery Compat doesn't execute any tests
on document ready, though so it could be aligned with master.

This makes jQuery Compat support tests work correctly even if jQuery is
included & used in head before body even exists - making it similar to
the master behavior.

Fixes gh-2502

EDIT: BTW, this PR decreases the gzipped size by 5 bytes. ;)

### CODE REVIEW

**Comment by mzgol** [comment]
Once this lands (I'd appreciate a quick review of this PR, @jquery/core), I'll work on a basic test suite for Android 2.3.

@timmywil @gibson042 Am I right that you prefer to not remove [Android 2.3 workarounds like this one](https://github.com/jquery/jquery/blob/6044fb6a7384aec85906949835ef9a58114896ce/test/unit/ajax.js#L1455-L1460) from `master` tests even when Android 2.3 won't even be reaching that code to reduce divergence from `master`? I guess we won't backport new Android 2.3-specific workarounds from `compat` to `master` so the divergence will happen anyway but whatever you prefer.

**Comment by gibson042** [comment]
> @timmywil @gibson042 Am I right that you prefer to not remove [Android 2.3 workarounds like this one](https://github.com/jquery/jquery/blob/6044fb6a7384aec85906949835ef9a58114896ce/test/unit/ajax.js#L1455-L1460) from `master` tests even when Android 2.3 won't even be reaching that code to reduce divergence from `master`? I guess we won't backport new Android 2.3-specific workarounds from `compat` to `master` so the divergence will happen anyway (and the "workarounds" are mainly skipping the test which is easy to isolate) but whatever you prefer.

My preference is for everything under `/test` to be identical between branches, so we don't run into unnecessary merge conflicts. We may not get there, but I definitely don't want to invest effort in explicit divergence.

**Comment by gibson042** [comment]
:clap:

This looks great, @mzgol.

**Comment by timmywil** [comment]
> We may not get there, but I definitely don't want to invest effort in explicit divergence.

Agreed.

**Comment by dmethvin** [comment]
Yes, merge conflicts are a pain so isolating those would be very helpful. That will become really clear if we ever do a style sweep on the unit tests!

**Comment by mzgol** [comment]
> We may not get there, but I definitely don't want to invest effort in explicit divergence.

@gibson042 @timmywil @dmethvin works for me. You should all like this PR, then, since it makes `src/**` more similar between `master` & `compat`. ;)

**Pull request merged**
