### PR TITLE
Build: Don't lint every file in dist/

### PR DESCRIPTION
**Pull request by mgol**
### Summary ###

Currently the "all" target for the eslint task includes way more than
the "dev" & "dist" targets combined and those 2 tasks are the one run in
`npm test`.

### Checklist ###
Mark an `[x]` for completed items, if you're not sure leave them unchecked and we can assist.

* [x] All authors have signed the CLA at https://contribute.jquery.com/CLA/
* [x] ~~New tests have been added to show the fix or feature works~~
* [x] Grunt build and unit tests pass locally with these changes
* [x] ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~

### CODE REVIEW

**Comment by mgol** [comment]
cc @markelog

**Comment by timmywil** [comment]
I wonder if we could also move the eslint comment that shows up at the top of [`dist/jquery.js`](https://code.jquery.com/jquery-3.1.0.js) to the closure (or at least below the banner).

**Comment by mgol** [comment]
This comment is no longer there. It used to be stripped when we used
JSHint; the regex was changed to a too-strict one when we migrated to
ESLint and that's why it showed up in jQuery 3.1.0. I've landed a fix some
time ago.

-- 
Michał Gołębiowski

**Comment by timmywil** [comment]
@mgol Thanks

**Comment by markelog** [comment]
Cool

**Pull request merged**
