### PR TITLE
http://cdn.bootcss.com/bootstrap/3.2.0/fonts/glyphicons-halflings-regular.woff

### PR DESCRIPTION
**Pull request by manlen**

### CODE REVIEW

**Comment by timmywil** [comment]
@yiminghe Not sure what happened here, but make sure this manlen gets access revoked and resubmit this PR.

**Comment by mgol** [comment]
@timmywil I've looked closer; there is nothing to resubmit here, this is PR #1005 (landed long ago) re-submitted by a spammer.

**Comment by rmccullagh** [comment]
What is the value of spamming in this context?

**Comment by timmywil** [comment]
@rmccullagh Who knows, maybe they really like bootstrap icons.

**Pull request closed without merging**
