### PR TITLE
Remove link from comment

### PR DESCRIPTION
**Pull request by ncklengyel**
### Summary ###
Remove link from comment

Fixes gh-4981

### Checklist ###

* [ ] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by mgol** [comment]
Can you also remove the other web archive link? Also, please sign our CLA.

**Comment by mgol** [comment]
Closing for lack of response.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Pull request closed without merging**
