### PR TITLE
Сore: Inline getProto

### PR DESCRIPTION
**Pull request by peasemaker**
### Checklist ###
Mark an `[x]` for completed items, if you're not sure leave them unchecked and we can assist.

* [x] All authors have signed the CLA at https://contribute.jquery.com/CLA/
* [ ] New tests have been added to show the fix or feature works
* [x] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

Thanks! Bots and humans will be around shortly to check it out.

### CODE REVIEW

**Comment by mgol** [comment]
What's the reason for this change?

Also, note that you committed your project settings. Never do `git add .`, it causes problems like that.

**Comment by scottgonzalez** [comment]
> Also, note that you committed your project settings. Never do git add ., it causes problems like that.

`git add .` is fine, given a better workflow. For starters, you should use `core.excludesfile` to ignore files like the `.idea` directory across all projects (see https://help.github.com/articles/ignoring-files/#create-a-global-gitignore). You should also review your diff before committing so that you know the changes you're committing are what you intended (this goes beyond just which files are being committed).

**Comment by mgol** [comment]
@peasemaker I'd still like to know what's the reason for this change.

**Comment by markelog** [comment]
>  I'd still like to know what's the reason for this change.

Same here

**Comment by TechQuery** [comment]
@mgol @markelog , I don't understand why jQuery needs to **make a separate module with only one ECMA / W3C API return-statement in it**...

**Comment by timmywil** [comment]
Thanks for opening a PR. I think this qualifies as bikeshedding though. We have some variables in separate modules so that those variables can be shared across modules without affecting the size of built jQuery. Moving it inline might mean we have to move it back out later if another module wants to use it (which I would not say is unlikely). And, moving it inline has very little affect on the built version.

**Pull request closed without merging**
