### PR TITLE
 Add possibly-unitless CSS grid properties

### PR DESCRIPTION
**Pull request by enbo**
### Summary ###

Fixes jquery/jquery#4007

### Checklist ###

* [x] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
* [ ] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by timmywil** [comment]
This needs tests, but can be merged in 3.4 once that happens.

**Comment by mgol** [comment]
@enbo Hey, will you have time to work on the tests soon? If not, please let us know so that we can proceed ourselves here. Thanks!

**Comment by enbo** [comment]
@mgol I apologize for the radio silence! Lots of transition going on in life right now so I won't be able to complete the tests soon.

**Comment by mgol** [comment]
Landed, thanks!

**Pull request merged**
