### PR TITLE
Ajax: Remove remnants of the load event alias handling

### PR DESCRIPTION
**Pull request by mzgol**
Refs 0705be475092aede1eddae01319ec931fb9c65fc
Refs gh-2287

cc @markelog

### CODE REVIEW

**Comment by markelog** [comment]
How did you find this?

**Comment by mzgol** [comment]
I just reminded myself that we had this duplicate logic and that I didn't see it removed in your PR so I found it. :)

**Comment by mzgol** [comment]
Hmm, I guess the `"../event/alias"` dependency can be removed as well?

**Comment by markelog** [comment]
> I just reminded myself that we had this duplicate logic

After a week it was landed? Your memory is an interesting thing :-)

**Comment by mzgol** [comment]
> After a week it was landed? Your memory is an interesting thing :-)

Actually, it was because jsFiddle broke on Git jQuery as they used the `.load()` shortcut and I searched for your commit to present it to them as the reason. And then it hit me when I looked at the diff. :)

**Comment by markelog** [comment]
> Actually, it was because jsFiddle broke on Git jQuery as they used the .load() shortcut and I searched for your commit to present it to them as the reason. And then it hit me when I looked at the diff. :)

:heart: :rage: both emotions there, we really need some tests for that kind of thing, i'd say we really need a code coverage tool here.

/cc @timmywil

**Comment by timmywil** [comment]
Yup, it's on the list! #1965

**Pull request closed without merging**
