### PR TITLE
[WIP] Drop the json-to-jsonp

### PR DESCRIPTION
**Pull request by raphamorim**
### Summary

Reference: https://github.com/jquery/jquery/issues/3376
### Checklist
- [ ] Write tests to check it
- [ ] Update jquery docs

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR! We definitely need tests to land in the same commit but this will only land in time for jQuery 4 so there's plenty of time.

**Comment by raphamorim** [comment]
Ok! I'll start work in the tests 👍

**Comment by mgol** [comment]
@raphamorim Are you still interested in finishing it? If not, let's close the PR.

**Comment by raphamorim** [comment]
Oh, I forgot about this PR. Closing it.

**Pull request closed without merging**
