### PR TITLE
Core: Deprecate jQuery.trim

### LINKED ISSUE #4363: Deprecate jQuery.trim?
### Description ###

[`jQuery.trim`](https://api.jquery.com/jQuery.trim/) was useful for IE <9 and later to workaround an old Android Browser issue but we don't support that browsers anymore on `master`. It also adds one niceity that it accepts a `null` value that it turns to an empty string but that's it. Should we deprecate it?

### PR DESCRIPTION
**Pull request by ShashankaNataraj**
### Summary ###

Component: Core
 
- Moved `jQuery.trim()` from the `core.js` file into the `deprecated.js` file
- Moved corresponding unit test from `test/unit/core.js` to `test/unit/deprecated.js`
 
Fixes #4363

### Checklist ###

* [x] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
* [x] New tests have been added to show the fix or feature works
* [x] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR.

Please follow our guidelines, especially for commit messages: https://contribute.jquery.org/commits-and-pull-requests/

The PR title should be named in the same format as well.

**Comment by timmywil** [comment]
The code changes look good.

**Comment by mgol** [comment]
@ShashankaNataraj Please sign our CLA.

**Comment by timmywil** [comment]
Looks like you did sign the CLA, but one of the commits has different author info. You can fix this with `git commit --amend --author=ShashankaNataraj`

**Comment by ShashankaNataraj** [comment]
@mgol @timmywil Thanks for your guidance. I hope the above commits do the trick! The issue was I committed with my official mail ID in the git config.

The CLA was picking up my old email ID as I have contributed to jQuery before as well!

**Comment by ShashankaNataraj** [comment]
@mgol Does this look correct?

**Comment by mgol** [comment]
(I updated the PR title to match the proper format)

**Comment by ShashankaNataraj** [comment]
@mgol Will do, thanks!

**Comment by mgol** [comment]
Moving the milestone to `3.5.0` (deprecations can only happen in minor or major releases and previously we didn't plan a minor bump on the 3.x line); I cherry-picked the change (with some necessary modifications) in 56e73e0c4ae908c853c986aadeda7cfcf2df4f6f.

**Pull request merged**
