### PR TITLE
Updates Dependencies

### PR DESCRIPTION
**Pull request by CDAGaming**
### Summary ###
This PR Updates the Following Dependencies:
- Babel-Preset-ES2015: v6.6.0 > v6.24.1 (Minor)
- CommitPlease: v2.6.1 > v2.7.10 (Minor)
- Core-JS: v2.2.2 > v2.4.1 (Minor)
- Cross-Spawn: v2.2.3 > v5.1.0 (Major)
- ESlint-Config-JQuery: v1.0.0 > v1.0.1 (Minor)
- Grunt-Contrib-Uglify: v1.0.1 > v3.0.1 (Major)
- Grunt-JSONLint: v1.0.7 > v1.1.0 (Minor)
- Grunt-Newer: v1.2.0 > v1.3.0 (Minor)
- Husky: v0.11.4 > v0.13.4 (Minor)
- Insight: v0.8.1 > 0.8.4 (Minor)
- Load-Grunt-tasks: v3.5.0 > v3.5.2 (Minor)
- Q: v1.4.1 > v1.5.0 (Minor)
- QUnit-Assert-Step: v1.0.3 > v1.1.1 (Minor)
- QUnitJS: v1.23.1 > v2.3.2 (Major)
- RequireJS: v2.2.0 > v2.3.3 (Minor)
- Simon: v1.17.3 > v2.3.2 (Major)

### Checklist ###
N/A

* [👍] All authors have signed the CLA at https://cla.js.foundation/jquery/jquery
* [👍] New tests have been added to show the fix or feature works
* [👍] Grunt build and unit tests pass locally with these changes
* [[Click Here](https://github.com/jquery/api.jquery.com/pull/1036)] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by all3fox** [comment]
Merging this PR right now will cause `commitplease` to be silently ignored by husky, I am investigating it.

**Comment by CDAGaming** [comment]
Nice, Thanks :)

**Comment by mgol** [comment]
Thanks for the PR.

Have you verified tests work after upgrading to QUnit 2? I tried that some time ago and they were failing.

**Comment by CDAGaming** [comment]
I do not remember the exact results @mgol, so ill rerun tests in a few hours, and will note results

**Comment by CDAGaming** [comment]
@mgol Yup, definitely errors on testing

**Comment by CDAGaming** [comment]
Will see if it's specifically QUnit causing this or another dependency(Pretty sure it's one of the major update dependencies if not QUnit)

**Comment by mgol** [comment]
@CDAGaming This error is unrelated, maybe the Promises/A+ tests are not working on Windows on cmd.exe? Have you tried Git Bash?

I was talking about [running the unit tests](https://github.com/jquery/jquery#running-the-unit-tests); you need to open a test page manually in a browser to see if it passes the tests.

**Comment by CDAGaming** [comment]
@mgol Sorry for the Late Response, and it seems that it was passing the tests, although even with git bash i was unable to do npm run test on either official(this) or my PR Fork

**Comment by CDAGaming** [comment]
JSDom v6.0.0+ are not compatible
https://github.com/tmpvar/jsdom/commit/3c156b854784071b5ca6744afeac6b8af9bd97dc

**Comment by timmywil** [comment]
@CDAGaming How about we isolate all of the dependencies that we know can be updated without issues and do those first?

**Comment by CDAGaming** [comment]
Ok, that would be the Minor Updated Dependencies(Ex: v1.2.3 to v1.2.4 or v1.2.3 to v1.3.4 NOT v1.2.3 to v2.0.0)

**Comment by CDAGaming** [comment]
I've updated the description as well as here are the Major Dep Updates:

- Cross-Spawn: v2.2.3 > v5.1.0 (Major)
- Grunt-Contrib-Uglify: v1.0.1 > v3.0.1 (Major)
- QUnitJS: v1.23.1 > v2.3.2 (Major)
- Simon: v1.17.3 > v2.3.2 (Major)

**Comment by mgol** [comment]
@CDAGaming Not necessarily. A lot of times breaking changes are in APIs we don't use; I'd say even most of times. What's needed is to update the deps and see if our build process/tests still work. Or look at the changelogs of updated libraries to read about breaking changes.

**Comment by CDAGaming** [comment]
Ah, Okay. I'll individually tests these dependencies and see which ones have breaking changes

**Comment by timmywil** [comment]
Merged in https://github.com/jquery/jquery/commit/31783e60f5649b194128a6e39404617c69117dab

**Pull request closed without merging**
