### PR TITLE
Add Node v0.12 and iojs to .travis.yml

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
I would like to upgrade .travis.yml.
node.js v0.12 and add io.js are released.

### CODE REVIEW

**Comment by yosuke-furukawa** [comment]
oops, I forgot CLA. sorry for missing CLA.

**Comment by mzgol** [comment]
@yosuke-furukawa You can sign the CLA & reopen. This LGTM afterwards.

**Comment by yosuke-furukawa** [comment]
I send a CLA.  But jQuery Foundation CLA does not check my CLA....

**Comment by arthurvr** [comment]
Isn't this a dupe of https://github.com/jquery/jquery/pull/2121?

**Comment by timmywil** [comment]
It sure is!

**Pull request closed without merging**
