### PR TITLE
Replaced jQuery.each with forEach to iterate arrays.

### PR DESCRIPTION
**Pull request by jackmoore**
All of the browsers supported by jQuery 2.x should support ES5 array iteration, so I don't see any benefit to using jQuery.each.  Just my preference for using native moving forward, feel free to close as the perf and file size differences would be insignificant.

### CODE REVIEW

**Comment by timmywil** [comment]
Thanks for contributing! However, we can't do this for backwards compatibility reasons.

**Comment by markelog** [comment]
@timmywil proposal here is to use `Array#forEach` internally

**Comment by timmywil** [comment]
So it is! However, haven't we also talked about that and decided it wasn't
worth it?

**Comment by markelog** [comment]
Don't remember such discussion, maybe a missed it, i'd say it is only worth it, if it helps to reduce the size, otherwise eat your own dog food.

**Comment by timmywil** [comment]
Ok, well I think I can recall the major points. 

1. The point @markelog brought up is a good one. We want to dog food our own methods.
2. IE8 doesn't have native `forEach` and we want to avoid diverging from the compat branch where it's not necessary or has no significant advantages.
3. It's not a perf issue.
4. Even if it is reduced size, the difference would not be enough to warrant ignoring the other points.

Just as a side note for future contributions, the 2.1-stable branch is not under active development and there are currently no plans to add any changes to that branch.

**Comment by jackmoore** [comment]
Thanks, I appreciate the explanation.

**Pull request closed without merging**
