### PR TITLE
Data: Use a PDF object instead of a Java applet for acceptData testing

### PR DESCRIPTION
**Pull request by mzgol**
This should fix "Java out of date" errors on BrowserStack.

Fixes gh-1938

### CODE REVIEW

**Comment by dmethvin** [comment]
So always BrowserStack pre-installs the PDF viewer on IE? If so then this is a good solution, at least until Adobe desupports *that*. :smile:

**Comment by rwaldron** [comment]
This is BRILLIANT!

**Comment by mzgol** [comment]
> So always BrowserStack pre-installs the PDF viewer on IE?

At least it does so on IE9 & IE8. :)

Credits to @gibson042 for the idea!

**Comment by gibson042** [comment]
LGTM :+1:

**Pull request merged**
