### PR TITLE
Docs: Fix typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
### Summary ###

Fixes typos found by [codespell](https://github.com/codespell-project/codespell).

### Checklist ###

* [ ] New tests have been added to show the fix or feature works
* [X] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR. I see some other codespell errors reported, e.g. in traversing tests. Can you fix them all in one go?

**Comment by DimitriPapadopoulos** [comment]
You mean `datas` and `failer`?

I had kept `datas` as a neologism which means `data_list` or something like that, as in other projects it is often used as `for ( data in datas ) {`, but it's easy to change here.

And `failer` is often used as a neologism for a test/condition that fails.

**Comment by mgol** [comment]
`failer` seems fine, `traversing` has `childs`, though, which seems wrong. Here's what I got (obviously, many of these results are wrong):
```
$ codespell --skip="AUTHORS.txt,./amd,./dist,./external,./node_modules,package-lock.json,./test/data/jquery-1.9.1.js"
./package.json:113: clos ==> close
./test/unit/selector.js:200: visble ==> visible
./test/unit/event.js:652: zar ==> czar
./test/unit/event.js:657: zar ==> czar
./test/unit/attributes.js:1178: te ==> the, be, we, to
./test/unit/attributes.js:1186: te ==> the, be, we, to
./test/unit/attributes.js:1187: te ==> the, be, we, to
./test/unit/attributes.js:1193: te ==> the, be, we, to
./test/unit/attributes.js:1194: te ==> the, be, we, to
./test/unit/attributes.js:1286: fo ==> of, for, to, do, go
./test/unit/attributes.js:1287: fo ==> of, for, to, do, go
./test/unit/attributes.js:1754: te ==> the, be, we, to
./test/unit/attributes.js:1755: te ==> the, be, we, to
./test/unit/traversing.js:193: childs ==> children, child's
./test/unit/traversing.js:194: childs ==> children, child's
./test/unit/ajax.js:2714: overrided ==> overrode, overridden
./test/unit/data.js:599: datas ==> data
./test/unit/data.js:638: datas ==> data
./test/unit/data.js:659: datas ==> data
./test/unit/data.js:731: datas ==> data
./test/unit/data.js:742: datas ==> data
./test/unit/data.js:760: datas ==> data
./test/unit/data.js:779: datas ==> data
./test/unit/data.js:793: datas ==> data
./test/unit/deferred.js:697: failer ==> failure
./test/unit/deferred.js:709: failer ==> failure
./test/unit/deferred.js:709: failer ==> failure
./test/unit/css.js:1412: convertable ==> convertible
./test/unit/css.js:1417: convertable ==> convertible
./test/unit/css.js:1418: convertable ==> convertible
./build/tasks/build.js:63: optIn ==> option
./build/tasks/build.js:278: optIn ==> option
./src/manipulation/domManip.js:78: Reenable ==> Re-enable
```

**Comment by DimitriPapadopoulos** [comment]
Indeed. I was used to seeing `childs` used as a list of `child` items, the same way `datas` is used as a list of `data` items. But here it's a genuine misspelling in an error message.

Fixed.

**Comment by DimitriPapadopoulos** [comment]
And yes, the rest are false positives, except `datas` and `failer` which are not real words but make sense in this context.

**Review by mgol — APPROVED** [review]
Thanks!

**Comment by mgol** [comment]
Landed on `main` in 620870a1af5287d29c77ec6d5f973116b23793a7 & in `3.x-stable` in 4a29888c759d0ca9a3ef7be90a2d7936cc48f5c8.

**Pull request merged**
