### PR TITLE
Build: Separate the install step from running tests in GitHub Actions

### PR DESCRIPTION
**Pull request by mgol**
### Summary ###

Separate the install step from running tests in GitHub Actions.
Also, update the "Run test" label to "Run tests".

### Checklist ###

* [ ] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Review by timmywil — APPROVED** [review]
Easy approval

**Comment by Mansalol** [comment]
T

**Comment by mgol** [comment]
Landed on `main` in eef972508c8be6cc3cd0039d34dc9fe16bac916c and on `3.x-stable` in cb35067f1b16661fa865f4f4e31132e37f5f4091.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Pull request merged**
