### PR TITLE
Cache the type result in variable

### PR DESCRIPTION
**Pull request by hapjs**
### Checklist ###
Mark an `[x]` for completed items, if you're not sure leave them unchecked and we can assist.

* [x] All authors have signed the CLA at https://contribute.jquery.com/CLA/
* [ ] New tests have been added to show the fix or feature works
* [ ] Grunt build and unit tests pass locally with these changes
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

Thanks! Bots and humans will be around shortly to check it out.

### CODE REVIEW

**Comment by gibson042** [comment]
Thanks for the pull request, but this actually has a detrimental effect on file size:
```
   raw     gz Sizes                                                            
267219  79077 dist/jquery.js                                                   
 86815  30052 dist/jquery.min.js                                               

   raw     gz Compared to master @ f18ca7bfe0f5e3184bf1ed55daf1668702c5577a    
   +17     +4 dist/jquery.js                                                   
     =     +9 dist/jquery.min.js                                               
```

**Comment by hapjs** [comment]
Yes, you are right.

**Comment by microlv** [comment]
@gibson042 May I ask you, what's tool do you use for compare file size?

**Comment by gibson042** [comment]
Our default `grunt` task's `grunt-compare-size`.

**Pull request closed without merging**
