### PR TITLE
Attributes:Fix get attribute on Document Fragments

### PR DESCRIPTION
**Pull request by Brooooooklyn**
should never trying to call getAttribute on DocumentFragment

http://jsbin.com/qoficotogo/1/edit?html,js,output

### CODE REVIEW

**Comment by timmywil** [comment]
Thanks for submitting a PR. However, first open an issue with a test case from http://jsfiddle.net or http://jsbin.com so we can review. Once the issue has been verified, this PR will need to add tests.

**Comment by gibson042** [comment]
Also note that our general trend has been to allow exceptions from invalid input:
* #2320
* #2134
* #2248

So generally speaking, this would be better fixed in the code that calls jQuery.

**Comment by Brooooooklyn** [comment]
```
    $(document).ready(function() {
      $(document).on('click', '[data-time="123"]', function() {
        console.log('never reached');
      });
      var frag = $(document.createDocumentFragment());
      var ele = $('<div class="wrap"><button class="btn btn-danger btn-cancel">click me!!!!!!!</button></div>');
      $(document.body).append(ele);
      $('.btn-cancel').on('click', function() {
        frag.append(ele);
      });
    });
```

consider about these code, how could I avoid this issue? I'm wondering if I shounldn't use documentFragment to cache my DOM, or I shouldn't use attributes selector in event listener?

I think jQuery shouldn't getAttribute from a documentFragment anytime.

This is the online DEMO: `http://jsbin.com/qoficotogo/1/edit?html,js,output`

**Comment by gibson042** [comment]
Ah, that looks like a duplicate of #2529, which was fixed by 9d820fbde6d89bc7a06e2704be61cf6c0b4d6e3c (but not yet released). You can confirm by loading jQuery from https://code.jquery.com/jquery-git.js .

**Pull request closed without merging**
