### PR TITLE
compat - Update code style, partially use new qunit interface, give test module a new name

### PR DESCRIPTION
**Pull request by markelog**
Same as https://github.com/jquery/jquery/pull/2542 to compat branch

Also incorporates #2504 and cherry-picks 63a577a. References to master commits will be added when pr to master will be landed.

ajax tests added selectively from master branch, should be all included, but it would be cool if someone would verify it.

### CODE REVIEW

**Comment by markelog** [comment]
@timmywil, @mzgol i'm gonna land this then, since we need this for the other prs

**Comment by mzgol** [comment]
> @timmywil, @mzgol i'm gonna land this then, since we need this for the other prs

Yeah, it's hard to review such a big thing quickly and since it's an analogous of the `master` version that we already looked at, feel free to land. :) Any issues that pop up can be addressed later, let's get this monster merged!

**Comment by timmywil** [comment]
> i'm gonna land this then, since we need this for the other prs

:+1:

**Comment by markelog** [comment]
Landed via https://github.com/jquery/jquery/compare/3923bb8400...cbb0be6c41

**Pull request closed without merging**
