### PR TITLE
Core: organize prop & attr code to be similar

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by markelog** [comment]
Closed via https://github.com/jquery/jquery/commit/d0388e9e806ca3b30e7bbaaa1c336b7c98dc5f88

**Comment by markelog** [comment]
It seems we have a failure in IE8 - http://swarm.jquery.org/result/407034, http://swarm.jquery.org/result/407032, could you please check it out?

**Comment by pgilad** [comment]
@markelog Is it relevant only for the compat branch?

**Comment by markelog** [comment]
Yes

**Comment by pgilad** [comment]
I would revert it for now, it's was a bad merge to the `compat` branch from the `master` branch

**Comment by markelog** [comment]
We decided wait for a day, will you able to make it?

**Comment by pgilad** [comment]
Yes

**Comment by pgilad** [comment]
@markelog https://github.com/jquery/jquery/pull/2427 (hopefully :smile_cat: )

**Pull request closed without merging**
