### PR TITLE
Update pseudos.js

### PR DESCRIPTION
**Pull request by yunusemrejr**
### Checklist ###

* [ ] New tests have been added to show the fix or feature works
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Review by mgol — CHANGES_REQUESTED** [review]
What are you trying to achieve here? You didn’t write any description or tests.

Closing for now. If there’s a real need for this PR, we can reopen, but you should explain what’s going on.

**Comment by yunusemrejr** [comment]
Hello mgol,

Apologies for the confusion; it looks like I accidentally removed the explanation in my commit.

To clarify: I refactored the original code by splitting the regex into individual constants like quotedArguments and simpleArguments. My aim was to improve readability and make future modifications easier. By isolating each pattern and adding contextual names, it should now be more manageable to adjust specific sections, such as adding support for new pseudo-classes or modifying the handling of quoted arguments.

Thank you for your patience, and I apologize again for the missing details.

**Comment by mgol** [comment]
@yunusemrejr as you can see, your modifications cause our unit tests to fail: https://github.com/jquery/jquery/actions/runs/11651148208/job/32440762990?pr=5578

Lint is also failing: https://github.com/jquery/jquery/actions/runs/11651148208/job/32440762853?pr=5578

Also, this PR is making the final minified gzipped code size larger than before. We care about this size a lot as jQuery is loaded on so many websites. In addition, I don't see a huge gain from dividing the regex into smaller parts; comments already explain what's going on and there are online regex visualizers.

**Comment by yunusemrejr** [comment]
Hello again mgol,
thanks for the feedback and explanation! I will keep these in mind the next time! 
Thanks, 
Yunus

**Pull request closed without merging**
