### PR TITLE
#2700 negative border and padding tests

### PR DESCRIPTION
**Pull request by vitaliyterziev**
additional tests and fixing typos in the old ones

### CODE REVIEW

**Comment by vitaliyterziev** [comment]
@timmywil something was completely wrong with my previous pull and credentials, i ran the grunt and all tests passed by the way. I will try to verify my credentials with this pull

**Comment by mgol** [comment]
@vitaliyterziev Thanks for the PR! Your commits need to be signed by your full name as well. Please don't re-sign the CLA, we'll delete the wrong entries (cc @scottgonzalez), just amend the commit with your full name as the author. Click on "Details" next to the failed CLA check for more info about configuring git for that etc.

**Comment by vitaliyterziev** [comment]
@mgol thanks for the clarifications and the guidance. All with the CLA seems fine now.

**Comment by vitaliyterziev** [comment]
@timmywil  I actually saw the problem in the style (the spacing) for better readability. Anyway this wasn't reported by the grunt run. I will fix it later

**Comment by mgol** [comment]
@vitaliyterziev Will you have time to fix the spacing issues? Tabs should be used and it's better to not modify existing lines unless necessary.

**Comment by vitaliyterziev** [comment]
@mgol i think that dimensions.js should be fine now, spaces are replaced by tabs and no unnecessary rows are touched

**Comment by mgol** [comment]
Landed, thanks!

**Pull request closed without merging**
