### PR TITLE
Build: Add dependabot.yml config (GitHub Actions)

### PR DESCRIPTION
**Pull request by coliff**
### Summary ###

Automated PRs to update GitHub Action versions.

I noticed some of the GitHub Action workflows were using older versions. It'd be good to use Dependabot to help keep them up-to-date.

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR. Can we make it monthly? We don't have a lot of commits landing in this repository and I don't think we need to update that quickly.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Can you do the same PR for `jquery-ui` https://github.com/jquery/jquery-ui

**Review by timmywil — APPROVED** [review]
LGTM

**Review by mgol — APPROVED** [review]

**Comment by mgol** [comment]
Landed on `main` in 3f8bb2a46daf76f1427f49810d06a210ffbc7016 and on `3.x-stable` in 5a363017cf80c3329bace5b45812a9dc10fcde7c.

**Pull request merged**
