### PR TITLE
Event: remove preDispatch hook & simplify "simulate" signature

### PR DESCRIPTION
**Pull request by markelog**
I bet there is more like that in there

/cc @dmethvin

### CODE REVIEW

**Comment by timmywil** [comment]
It doesn't take up much room. Maybe we should document?

**Comment by markelog** [comment]
> It doesn't take up much room. Maybe we should document?

Okay, so to not wiggle about with this pull, i will remove changes of `event.special` structure and just simplify the `simulate` method and create api ticket.

Sounds good?

**Comment by timmywil** [comment]
:+1:

**Comment by dmethvin** [comment]
Sounds good to me.

**Comment by timmywil** [comment]
Yup, +1

**Comment by markelog** [comment]
Yeah, yeah i got it :-), will land it soon

**Pull request closed without merging**
