### PR TITLE
arraylike

### PR DESCRIPTION
**Pull request by mhbseal**
More info at the issue: #2238

### CODE REVIEW

**Comment by mhbseal** [comment]
@gibson042 i already set config user.name and user.email.

**Comment by markelog** [comment]
Could you sign <a href="http://contribute.jquery.org/CLA/status/?repo=jquery&sha=d3aca93402e0cf076f67c2bea6cb4d49b7f19826">CLA</a>? 

Preferably with your real name from which you authored proposed commit.

**Comment by mhbseal** [comment]
@markelog  I used my real name, and tried many times, or not, I don't know why CLA: Error

**Comment by markelog** [comment]
That is probably because some of your commits are signed correctly others does not, could you squash to one commit?

**Comment by markelog** [comment]
Check this out - http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by mhbseal** [comment]
Thanks, i squash them to one commit, but it is CLA: Error, I used my real name.

**Comment by markelog** [comment]
@scottgonzalez could you help us out?

**Comment by mzgol** [comment]
Everything seems OK to me with your setup, @mhbseal.

**Comment by scottgonzalez** [comment]
The CLA was originally signed all lowercase. I've updated the signature and deleted the several duplicate signatures.

**Comment by markelog** [comment]
@scottgonzalez 

> The CLA was originally signed all lowercase.

Should checker be case-insensitive? 

> I've updated the signature and deleted the several duplicate signatures.

bot was confused because of the duplicates?

**Comment by scottgonzalez** [comment]
> Should checker be case-insensitive?

Potentially. I'd prefer if people just wrote their name properly.

> bot was confused because of the duplicates?

Only the first signature is used. All future signatures are discarded.

**Comment by markelog** [comment]
Maybe bot could collect all signatures and choose the right one with correct case? So we wouldn't confuse people when they correct their signature?

**Comment by scottgonzalez** [comment]
This has been discussed to death. Please move any discussion to the appropriate repo.

**Comment by mhbseal** [comment]
Thank you all

**Pull request closed without merging**
