### PR TITLE
Build: Update QUnit to latest (1.17.1)

### PR DESCRIPTION
**Pull request by jzaefferer**
Running `grunt npmcopy` also updated requirejs and sinon. The sinon changes looked like they'd actually break something, so I ignored them both. Can't tell why the dependencies were updated without updating the copies in the repo.

### CODE REVIEW

**Comment by mzgol** [comment]
> Running `grunt bowercopy`

You mean `grunt npmcopy`?

**Comment by jzaefferer** [comment]
Yes yes, that.

**Comment by jzaefferer** [comment]
* [ ] Yes
* [ ] No
* [ ] Maybe

**Comment by mzgol** [comment]
Since nothing changed in Core files, LGTM.

We should get the libs copies synced with what's in package.json btw...

**Comment by jzaefferer** [comment]
Well, I'll leave that exercise to someone who's more familiar with those updated dependencies.

**Comment by markelog** [comment]
If there is no objections - will land this tomorrow

**Comment by markelog** [comment]
Hm, since this update broke couple traversing and manipulation tests, since new qunit added another form to the test-suite and some of jQuery selectors weren't specific.

Will fix that up.

**Pull request closed without merging**
