### PR TITLE
CSS: Make the reliableTrDimensions support test work with Bootstrap CSS (3.x version)

### PR DESCRIPTION
**Pull request by mgol**
### Summary ###

3.x version of PR #5278.

Bootstrap 5 includes the following CSS on the page:

```css
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

That threw our `reliableTrDimensions` support test off. This change fixes the support test and adds a unit test ensuring support test values on a page including Bootstrap 5 CSS are the same as on a page without it.

Fixes gh-5270
Ref gh-5278

+8 bytes

### Checklist ###

* [x] New tests have been added to show the fix or feature works
* ~~If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com~~

### CODE REVIEW

**Comment by mgol** [comment]
+8 bytes

**Comment by angeljqv** [comment]
Great! 👍

**Review by timmywil — APPROVED** [review]
Thanks for adding the test.

**Comment by angeljqv** [comment]
Hi, 3.7.1 release date??

**Comment by mgol** [comment]
@angeljqv there are no blockers for the release now, so we'll release when we have a moment. We never promise specific dates, though.

**Pull request merged**
