### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by jsoref**
Please feel free to squash/whatever;
No testing was done on this.
I've intentionally omitted fixes for `external/` (there are 9), I'll try to find the appropriate upstreams for them...

### CODE REVIEW

**Comment by pali88** [comment]
Apdate

**Comment by pali88** [comment]
Free

**Comment by markelog** [comment]
Did you did this manually or with some tool?

**Comment by markelog** [comment]
Btw, would you mind signing CLA?

**Comment by jsoref** [comment]
@markelog : I have a `tool` (a tiny perl script) which identifies word-ish tokens (basically it splits thisAndThat and similar things), and then I just visually review all of the word-ish things using a text editor w/ a spellchecker enabled.

It is possible to take the word-ish thing and make a whitelist of "acceptable odd terms" and then complain when anyone adds a term to the output w/o also adding it to the whitelist, if you're so inclined...

**Comment by dmethvin** [comment]
That's a really awesome tool! It's great to get all these fixed in a single PR.

**Comment by timmywil** [comment]
This is great, but we'll need to leave out all of the fixes in the `external` folder.

**Comment by timmywil** [comment]
Which seems to be all of them. :/

**Comment by timmywil** [comment]
However, this *could* be done on the Sizzle and QUnit repos.

**Comment by jsoref** [comment]
Whoops. Sorry. 

I really was trying to keep the external stuff separate. But when I updated to split things around, I ended up pushing the externals instead of the internals.

The new pull request which I hopefully won't mess up is: https://github.com/jquery/jquery/pull/2761

**Pull request closed without merging**
