### PR TITLE
Event: Fix chaining .on() with null handlers

### PR DESCRIPTION
**Pull request by dwilson6**
This is to fix https://github.com/jquery/jquery/issues/2812

### CODE REVIEW

**Comment by mgol** [comment]
Thanks. I'd normally want a unit test for that but since it's officially unsupported it LGTM. If we wanted to start officially support it we'd need to add tests.

**Comment by markelog** [comment]
We can add test, which would check that return value is not `window` object or that it is a jQuery object.

**Comment by mgol** [comment]
Yeah, we could. @dwilson6 could you modify the test at https://github.com/jquery/jquery/blob/df31b88135f94f903c8a887085d30d085a9c62f6/test/unit/event.js#L8-L21 to not test whether this method throws but to check if the returned value is the original element? We would backport the test to the `1.12-stable` branch as well.

P.S. In the future, it's a good idea to create a separate branch for each patch you create. `master`, `2.2-stable` etc. should be used only to pull from the main jQuery repository, you shouldn't modify them. Otherwise if you needed to pull the newest changes from our repository it may be non-trivial to do.

**Comment by dwilson6** [comment]
Yeah, I was wondering if it was worth a test. I can do that. And thanks for the tip.

**Comment by timmywil** [comment]
Merged.

**Pull request closed without merging**
