### PR TITLE
CSS: Add an integration test for issue gh-1764

### PR DESCRIPTION
**Pull request by mzgol**
Refs gh-1764
Refs gh-2401

Screenshots in IE11:
1. not fullscreen:
screen shot 2015-06-23 at 01 42 16
2. fullscreen without the patch: 
screen shot 2015-06-23 at 01 42 34
3. fullscreen with the patch: 
screen shot 2015-06-23 at 01 53 59

### CODE REVIEW

**Comment by markelog** [comment]
This is ported from http://christophercurrie.github.io/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html?

**Comment by mzgol** [comment]
No, written from scratch. I wanted to make it as similar to the `compat` PATCH test as possible.

**Comment by mzgol** [comment]
@timmywil @markelog is it OK to land?

**Comment by markelog** [comment]
This probably would need to be changed anyway if/when we integrate e2e-testing, so if it works now it is LGTM.

**Comment by mzgol** [comment]
I forgot: I should add another div on the page that's not in an iframe to
ensure we're correcting the output only when it's wrong. The script needs
to be extracted to avoid the duplication. I'll update the PR tomorrow.

-- 
Michał Gołębiowski

**Comment by mzgol** [comment]
I refactored the test; JS & CSS are now in separate files, shared by the main HTML & the iframe one.

**Comment by mzgol** [comment]
I'll land it tomorrow around noon European time or slightly later.

**Pull request closed without merging**
