### PR TITLE
Build: Reference GitHub Actions by commit SHAs

### PR DESCRIPTION
**Pull request by gabibguti**
### Summary ###
Resolves https://github.com/jquery/jquery/issues/5266

It's important to make sure the SHA's are from the original repositories and not forks. I have manually verified all of them and added references in the commit descriptions.

### Checklist ###

* [ ] New tests have been added to show the fix or feature works
* [ ] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

### CODE REVIEW

**Comment by mgol** [comment]
Thank you! Please sign the CLA.

**Comment by mgol** [comment]
@gabibguti Ping. Please sign the OpenJSF CLA, we cannot merge the PR otherwise.

**Comment by gabibguti** [comment]
Hi @mgol! Thanks for the reminder. I'm checking internally with Google if I can sign the CLA.

**Comment by mgol** [comment]
I see. If you're submitting this on company time, I think you'll need to chose the "Proceed as a Corporate Contributor" button.

**Comment by gabibguti** [comment]
@mgol Done!

**Review by mgol — APPROVED** [review]
Thanks!

**Comment by mgol** [comment]
Landed on `main` in 784b9ba6e403997161113aa56d1747baed4e0767 & on `3.x-stable` in 0ea85dadaa054a0d05b3b015456c8fc67ddfec4a.

**Pull request merged**
