### PR TITLE
Tests: Change quotes according to style guidelines

### PR DESCRIPTION
**Pull request by 64lines**
Modifies the quotes in the test files according to the style guidelines explained here: http://contribute.jquery.org/style-guide/js/#quotes

### CODE REVIEW

**Comment by markelog** [comment]
It seems we can `rm` those files.

/cc @timmywil

**Comment by timmywil** [comment]
Sure! Are they not used?

**Comment by markelog** [comment]
As i see they not used in testsuite, it looks like their function is to open them manually, but honestly, i didn't even know we had them.

**Comment by timmywil** [comment]
What about moving them to an `integration` folder? Eventually, we can automate running all pages in that folder using something like webdriver. The tests would still need adjustment, but we can get to that later.

**Comment by mzgol** [comment]
Note that `compat` already has the `test/integration` directory, currently containing just one test: https://github.com/jquery/jquery/tree/42ea7468250f1b612684a71b8643ae25367ff469/test/integration

**Comment by markelog** [comment]
> What about moving them to an integration folder?

Would still need to rewrite them, for example, there is page that uses `live()` in there. I'm not sure what we support in there.

**Comment by timmywil** [comment]
Good point, but, like I said, we can save the rewrites/removals for later.

**Comment by markelog** [comment]
So @lexinerus would like to do that? Make sure those tests are still relevant and if they are, rewrite them and move to `integration` folder?

**Comment by jzaefferer** [comment]
The CLA check is fine now.

**Comment by mzgol** [comment]
@markelog @timmywil I'd rather not have files not working with current jQuery in the `integration` folder. Perhaps in `integration/old` or `integration/legacy`, or `integration/to-rewrite` so that it's clear they're not expected to work currently?

**Comment by timmywil** [comment]
We don't run these tests very often. I don't think we need the reminder
with a folder name, just with an issue that tells us to rewrite these tests
and run them before final release.

**Comment by markelog** [comment]
I guess we need a .md doc for the release procedure, or we already have one? Since we doing more then just running one command

**Comment by mzgol** [comment]
> I guess we need a .md doc for the release procedure (or we already have one?). Since we doing more then just running one command

https://github.com/jquery/jquery/wiki/Release-process

**Comment by markelog** [comment]
Ah, thanks, okay so we would need to add another item there when we deal with update these tests

**Comment by timmywil** [comment]
Item added.

**Pull request closed without merging**
