### PR TITLE
Ajax: improve content-type detection

### PR DESCRIPTION
**Pull request by markelog**
Fixes gh-2584

/cc @jaubourg, @timmywil, @dmethvin

### CODE REVIEW

**Comment by jaubourg** [comment]
Don't forget the [script regexp](https://github.com/jquery/jquery/blob/master/src/ajax/script.js#L21) ;)

**Comment by markelog** [comment]
Done, looks good?

**Comment by jaubourg** [comment]
Looks awesome!

**Comment by markelog** [comment]
@jaubourg it is your solution, i'm just typing monkey :-)

**Pull request closed without merging**
