### PR TITLE
Build: Include the source code in the source map.

### PR DESCRIPTION
**Pull request by blainesch**
### Summary ###

This adds the source code to the source map, so it is more useful for developers.

### Checklist ###
Mark an `[x]` for completed items, if you're not sure leave them unchecked and we can assist.

* [x] All authors have signed the CLA at https://contribute.jquery.com/CLA/
* [x] New tests have been added to show the fix or feature works
* [x] Grunt build and unit tests pass locally with these changes
* [x] If needed, a docs issue/PR was created at https://github.com/jquery/api.jquery.com

Thanks! Bots and humans will be around shortly to check it out.

### CODE REVIEW

**Comment by dmethvin** [comment]
@blainesch  How much bigger is the map with this option enabled?  Obvs it won't be loaded by most users but I just wonder about the size.

**Comment by blainesch** [comment]
@dmethvin it went from 129k to 424k.

**Comment by mgol** [comment]
Why is this more useful for web developers?

**Comment by blainesch** [comment]
@mgol I find it difficult to imagine a source map being useful at all without the source.

**Comment by mgol** [comment]
@blainesch The source map doesn't have to _include_ the source, it may just reference it and our map file does this, just look at the `sources` property in the map file; it contains reference to the unminified `jquery.js`.

What problems would inlining the source solve for you?

**Comment by markelog** [comment]
There is no response from ticket owner for over the week now, so i'm closing this. Please let us know if you want to continue this discussion

**Pull request closed without merging**
